//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public string IdNumber { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string FatherProfession { get; set; }
        public string MotherProfession { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Student_No { get; set; }
        public string Student_Name { get; set; }
        public Nullable<bool> Is_Active { get; set; }
    }
}
